2021-02-28T19:02:19.048556+00:00 app[run.7120]: 2021-02-28 19:02:19,048 (__init__.py:515 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Unclosed start tag at byte offset 22"

.../
120]: user_id: 699642076
2021-02-28T16:14:44.235984+00:00 app[run.7120]: query: Текст, выражающий в примере. 1 — число, 2 — также. Тест-тест
2021-02-28T19:02:19.048556+00:00 app[run.7120]: 2021-02-28 19:02:19,048 (__init__.py:515 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Unclosed start tag at byte offset 22"
2021-02-28T21:21:33.752502+00:00 app[run.7120]: user_id: 699642076
2021-02-28T21:21:33.754504+00:00 app[run.7120]: query: пример теп
./


//
nic-bot... done

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>heroku run:detached python worker.py -a=old-slavonic-bot
Running python worker.py on ⬢ old-slavonic-bot... done, run.2796 (Free)
Run heroku logs --app old-slavonic-bot --dyno run.2796 to view the output.

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>heroku logs --app old-slavonic-bot --dyno run.2796
2021-03-01T15:38:39.699451+00:00 heroku[run.2796]: Starting process with command `python worker.py`
2021-03-01T15:38:40.524572+00:00 heroku[run.2796]: State changed from starting to up
2021-03-01T15:38:42.778684+00:00 app[run.2796]: Parsing the beginning of configs' file.
2021-03-01T15:38:44.121349+00:00 app[run.2796]: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: query is too old and response timeout expired or query ID is invalid
2021-03-01T15:38:44.134842+00:00 app[run.2796]: user_id: 699642076
2021-03-01T15:38:44.134846+00:00 app[run.2796]: query: j
2021-03-01T15:38:44.540871+00:00 app[run.2796]: user_id: 699642076
2021-03-01T15:38:44.540921+00:00 app[run.2796]: query: т
2021-03-01T22:19:59.522094+00:00 app[run.2796]: user_id: 699642076
2021-03-01T22:19:59.523866+00:00 app[run.2796]: query: т
2021-03-02T15:48:48.158726+00:00 heroku[run.2796]: Cycling
2021-03-02T15:48:48.165574+00:00 heroku[run.2796]: State changed from up to complete
2021-03-02T15:48:49.279256+00:00 heroku[run.2796]: Stopping all processes with SIGTERM
2021-03-02T15:48:49.423656+00:00 heroku[run.2796]: Process exited with status 143

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot># T: 21:00
"#" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

/.



//

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>heroku run:detached python worker.py -a=old-slavonic-bot
Running python worker.py on ⬢ old-slavonic-bot... done, run.9460 (Free)
Run heroku logs --app old-slavonic-bot --dyno run.9460 to view the output.

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>heroku logs --app old-slavonic-bot --dyno run.9460heroku logs --app old-slavonic-bot --dyno run.9460^Z^Z
 »   Error: Unexpected argument: logs
 »   See more help with --help

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>heroku logs --app old-slavonic-bot --dyno run.9460
2021-03-03T19:37:30.759892+00:00 heroku[run.9460]: Starting process with command `python worker.py`
2021-03-03T19:37:31.407697+00:00 heroku[run.9460]: State changed from starting to up
2021-03-03T19:37:33.070541+00:00 app[run.9460]: Parsing the beginning of configs' file.

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>heroku logs --app old-slavonic-bot --dyno run.9460
2021-03-03T19:37:30.759892+00:00 heroku[run.9460]: Starting process with command `python worker.py`
2021-03-03T19:37:31.407697+00:00 heroku[run.9460]: State changed from starting to up
2021-03-03T19:37:33.070541+00:00 app[run.9460]: Parsing the beginning of configs' file.
2021-03-04T09:36:47.903704+00:00 app[run.9460]: user_id: 699642076
2021-03-04T09:36:47.903841+00:00 app[run.9460]: query: Панятно

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>heroku stopПривет можешь попросить, чтобы мне дали доступ к просмотру лекций по гармоническому анализу. Вот моя почта:
 »   Warning: stopПривет is not a heroku command.
Did you mean stop? [y/n]: il.lazarashvili@gmail.com^Zn
/


//
nic-bot>heroku logs --app old-slavonic-bot --dyno run.9520
2021-03-04T13:55:28.615087+00:00 heroku[run.9520]: Starting process with command `python worker.py`
2021-03-04T13:55:29.414391+00:00 heroku[run.9520]: State changed from starting to up
2021-03-04T13:55:32.360317+00:00 app[run.9520]: Parsing the beginning of configs' file.
2021-03-05T08:56:58.224760+00:00 app[run.9520]: user_id: 699642076
2021-03-05T08:56:58.224973+00:00 app[run.9520]: query: b
2021-03-05T08:56:59.132194+00:00 app[run.9520]: user_id: 699642076
2021-03-05T08:56:59.132216+00:00 app[run.9520]: query: b1
2021-03-05T14:01:07.091680+00:00 heroku[run.9520]: Cycling
2021-03-05T14:01:07.094111+00:00 heroku[run.9520]: State changed from up to complete
2021-03-05T14:01:08.808427+00:00 heroku[run.9520]: Stopping all processes with SIGTERM
2021-03-05T14:01:09.040907+00:00 heroku[run.9520]: Process exited with status 143

C:\Users\hp\Desktop\Repositories\Old-Slavonic-bot>
//----
Microsoft Windows [Version 10.0.19041.804]
(c) Корпорация Майкрософт (Microsoft Corporation), 2020. Все права защищены.

C:\Users\hp>heroku login
heroku: Press any key to open up the browser to login or q to exit:
Opening browser to https://cli-auth.heroku.com/auth/cli/browser/e5e28266-710f-4f59-8005-0712dd12749d?requestor=SFMyNTY.g2gDbQAAAAwzNy41My4xNDUuODZuBgCo0ZkHeAFiAAFRgA.ZORruQewS7ljTIocMWOgjhyI4l6N8iuqCAn9xHurZyg
heroku: Waiting for login... |
^CЗавершить выполнение пакетного файла [Y(да)/N(нет)]? y

C:\Users\hp>heroku login
heroku: Press any key to open up the browser to login or q to exit:
Opening browser to https://cli-auth.heroku.com/auth/cli/browser/0be175fa-1354-4a40-95ed-a08d8f01c1be?requestor=SFMyNTY.g2gDbQAAAAwzNy41My4xNDUuODZuBgBRF5oHeAFiAAFRgA.YYMbZ2YpvtNzobYN2Fw-HGwSkBTtjyh4DkeYZYx4ljQ
Logging in... done
Logged in as me2001.com@gmail.com

C:\Users\hp>heroku run:detached python worker.py -a=old-slavonic-bot
Running python worker.py on ⬢ old-slavonic-bot... done, run.5741 (Free)
Run heroku logs --app old-slavonic-bot --dyno run.5741 to view the output.

C:\Users\hp>heroku logs --app old-slavonic-bot --dyno run.5741
2021-03-06T12:55:05.287239+00:00 heroku[run.5741]: Starting process with command `python worker.py`
2021-03-06T12:55:05.987102+00:00 heroku[run.5741]: State changed from starting to up
2021-03-06T12:55:07.646056+00:00 app[run.5741]: Parsing the beginning of configs' file.
2021-03-06T12:55:19.028453+00:00 app[run.5741]: 2021-03-06 12:55:19,028 (__init__.py:463 MainThread) ERROR - TeleBot: "Infinity polling exception: [Errno 2] No such file or directory: 'data/do_logs.log'"

C:\Users\hp>heroku logs --app old-slavonic-bot --dyno run.5741
2021-03-06T12:55:05.287239+00:00 heroku[run.5741]: Starting process with command `python worker.py`
2021-03-06T12:55:05.987102+00:00 heroku[run.5741]: State changed from starting to up
2021-03-06T12:55:07.646056+00:00 app[run.5741]: Parsing the beginning of configs' file.
2021-03-06T12:55:19.028453+00:00 app[run.5741]: 2021-03-06 12:55:19,028 (__init__.py:463 MainThread) ERROR - TeleBot: "Infinity polling exception: [Errno 2] No such file or directory: 'data/do_logs.log'"
2021-03-06T13:05:42.679597+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:05:42.679612+00:00 app[run.5741]: query: 12
2021-03-06T13:06:10.365034+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:10.365137+00:00 app[run.5741]: query: 1
2021-03-06T13:06:11.248380+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:11.248449+00:00 app[run.5741]: query: 1 год
2021-03-06T13:06:15.218686+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:15.218702+00:00 app[run.5741]: query: 1 год — 2
2021-03-06T13:06:15.463088+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:15.463238+00:00 app[run.5741]: query: 1 год — 12 м
2021-03-06T13:06:17.017076+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:17.017630+00:00 app[run.5741]: query: 1 год — 12 месф
2021-03-06T13:06:17.836082+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:17.836100+00:00 app[run.5741]: query: 1 год — 12 месяй
2021-03-06T13:06:18.338501+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:18.338516+00:00 app[run.5741]: query: 1 год — 12 месяц
2021-03-06T13:06:21.030697+00:00 app[run.5741]: user_id: 699642076
2021-03-06T13:06:21.032226+00:00 app[run.5741]: query: 1 год — 12 месяцев
2021-03-06T23:26:22.603227+00:00 app[run.5741]: 2021-03-06 23:26:22,477 (__init__.py:515 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2021-03-06T23:26:22.984687+00:00 app[run.5741]: 2021-03-06 23:26:22,984 (__init__.py:515 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"

C:\Users\hp>heroku stop
 »   Error: Missing 1 required arg:
 »   dyno
 »   See more help with --help

C:\Users\hp>heroku stop run.5741
 »   Error: Missing required flag:
 »     -a, --app APP  app to run command against
 »   See more help with --help

C:\Users\hp>heroku stop run.5741 --app old-slavonic-bot
Stopping run.5741 dyno on ⬢ old-slavonic-bot... done

C:\Users\hp>3
/